tap "homebrew/cask-fonts"
tap "homebrew/services"
tap "mikesmithgh/git-prompt-string"
# Manage your dotfiles across multiple diverse machines, securely
brew "chezmoi"
# Tool for emulating mouse and keyboard events
brew "cliclick"
# GNU File, Shell, and Text utilities
brew "coreutils"
# LCS based diff highlighting tool to ease code review from your terminal
brew "diffr"
# Pack, ship and run any application as a lightweight container
brew "docker", link: false
# Isolated development environments using Docker
brew "docker-compose", link: false
# Modern, maintained replacement for ls
brew "eza"
# GitHub command-line tool
brew "gh"

# Bash and Zsh completion for Gradle
brew "gradle-completion"
# Open-source video transcoder available for Linux, Mac, and Windows
brew "handbrake", link: false
# Kubernetes package manager
brew "helm"
# Improved top (interactive process viewer)
brew "htop"
# Kubernetes command-line interface
brew "kubernetes-cli"
# Tool that can switch between kubectl contexts easily and create aliases
brew "kubectx"
# Manage multiple Node.js versions
brew "nvm"
# Execute binaries from Python packages in isolated environments
brew "pipx"
# 7-Zip is a file archiver with a high compression ratio
brew "sevenzip"
# Command-line interface for https://speedtest.net bandwidth tests
brew "speedtest-cli"
# User interface to the TELNET protocol
brew "telnet"
# Internet file retriever
brew "wget"

# Compare files and folders
cask "beyond-compare"
# Tool to list all active shortcuts of the current application
cask "cheatsheet"
# Write, edit, and chat about your code with AI
cask "cursor"
# App to build and share containerised applications and microservices
cask "docker"
# Productivity app
cask "dropzone"
# Web browser focusing on privacy
cask "duckduckgo"
# Collaborative team software
cask "figma"
cask "font-hack-nerd-font"
# Set of tools to manage resources and applications hosted on Google Cloud
cask "google-cloud-sdk"
# Menu bar application that displays the CPU speed limit due to thermal issues
cask "hot"
# File archiver
cask "keka"
# Video format converter (transcoder)
cask "makemkv"
# Provides updates to various Microsoft products
cask "microsoft-auto-update"
# Meet, chat, call, and collaborate in just one place
cask "microsoft-teams"
# Set of tools to create, alter and inspect Matroska files (MKV)
cask "mkvtoolnix"
# App to write, plan, collaborate, and get organised
cask "notion"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Home media player
cask "plex"
# Collaboration platform for API development
cask "postman"

# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Team communication and collaboration software
cask "slack"
# General-purpose text editor
cask "textmate"
# Open-source code editor
cask "visual-studio-code"
# Rust-based terminal
cask "warp"


{{ if eq .machine "work" }}
cask "microsoft-teams"
cask "slack"
{{ else }}
# NAS management application
cask "qfinder-pro"
# Automatic file synchronisation
cask "qsync-client"
# Charting and social-networking for investment traders
cask "tradingview"
# Open-source BitTorrent client
cask "transmission"
# Video game digital distribution service
cask "steam"
# Remote access and connectivity software focused on security
cask "teamviewer"
# Messaging app with a focus on speed and security
cask "telegram"
# Open-source video transcoder
cask "handbrake"
# Native desktop client for WhatsApp
cask "whatsapp"
# Multimedia player
cask "vlc"
# Remote desktop application focusing on security
cask "vnc-viewer"

# Browser for SQLite databases
cask "db-browser-for-sqlite"
# Voice and text chat software
cask "discord"
# Video editor
cask "avidemux"
# Installer for BetterDiscord
cask "betterdiscord-installer"
{{ end }}
# Agentic IDE powered by AI Flow paradigm
cask "windsurf"
vscode "k--kato.intellij-idea-keybindings"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
